// Generated by CoffeeScript 1.7.1
(function() {
  window.Constant = {
    KEYCODE_ENTER: 13,
    KEYCODE_SPACE: 32,
    KEYCODE_UP: 87,
    KEYCODE_LEFT: 65,
    KEYCODE_RIGHT: 68,
    KEYCODE_W: 87,
    KEYCODE_S: 83,
    KEYCODE_A: 65,
    KEYCODE_D: 68,
    KEYCODE_Z: 90,
    KEYCODE_DOWN: 83,
    KEYCODE_J: 74,
    KEYCODE_K: 75,
    KEYCODE_L: 76
  };

}).call(this);
