// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Magic = (function(_super) {
    __extends(Magic, _super);

    function Magic(id, name, x, y, world, characterID, direction, spriteSheetInfo) {
      this.id = id;
      this.name = name;
      this.x = x;
      this.y = y;
      this.world = world;
      this.characterID = characterID;
      this.direction = direction;
      this.spriteSheetInfo = spriteSheetInfo;
      Magic.__super__.constructor.call(this, this.id, this.name, "magic", this.x, this.y, this.world);
      this.magic;
      this.damage = 10;
      this.init();
    }

    Magic.prototype.init = function() {
      this.SpriteSheet = new createjs.SpriteSheet(this.spriteSheetInfo);
      this.magic = new createjs.BitmapAnimation(this.SpriteSheet);
      this.magic.x = this.x;
      this.magic.y = this.y;
      this.magic.name = this.name;
      this.collisionHeight = 0;
      this.collisionWidth = 0;
      this.originSpeed = 5;
      this.speed = this.originSpeed;
      return this.cast();
    };

    Magic.prototype.cast = function() {
      if (this.direction === "left") {
        this.get().scaleX = -this.get().scaleX;
      }
      this.world.addObject(this);
      return this.magic.gotoAndPlay("cast");
    };

    Magic.prototype.get = function() {
      return this.magic;
    };

    return Magic;

  })(object);

}).call(this);
