// Generated by CoffeeScript 1.7.1
(function() {
  var Object;

  Object = (function() {
    function Object(name, type, x, y, stage, arena) {
      this.name = name;
      this.type = type;
      this.x = x;
      this.y = y;
      this.stage = stage;
      this.arena = arena;
      this.id;
      this.type;
      this.hp;
      this.mass = 1;
      this.speed;
      this.spriteSheetInfo;
      this.object = null;
      this.objectSpriteSheet;
      this.direction = "right";
      this.stage;
      this.arena;
      this.magicState = "ready";
      this.init();
    }

    Object.prototype.init = function() {};

    Object.prototype.get = function() {
      return this.object;
    };

    Object.prototype.changeDirection = function(direction) {
      this.direction = direction;
      return this.get().scaleX = -this.get().scaleX;
    };

    Object.prototype.reverseDirection = function() {
      switch (this.direction) {
        case "right":
          return this.direction = "left";
        case "left":
          return this.direction = "right";
        case "up":
          return this.direction = "down";
        case "down":
          return this.direction = "up";
      }
    };

    Object.prototype.moveStep = function(direction) {
      var bound;
      bound = this.arena.getBound();
      switch (direction) {
        case "left":
          if (this.direction !== "left") {
            this.changeDirection("left");
          }
          if (this.get().x - this.speed > bound['x1']) {
            return this.get().x -= this.speed;
          } else {
            return this.get().x += this.speed;
          }
          break;
        case "right":
          if (this.direction !== "right") {
            this.changeDirection("right");
          }
          if (this.get().x + this.speed < bound['x2']) {
            return this.get().x += this.speed;
          } else {
            return this.get().x -= this.speed;
          }
          break;
        case "down":
          if (this.get().y + this.speed < bound['y2']) {
            return this.get().y += this.speed;
          } else {
            return this.get().y -= this.speed;
          }
          break;
        case "up":
          if (this.get().y - this.speed > bound['y1']) {
            return this.get().y -= this.speed;
          } else {
            return this.get().y += this.speed;
          }
      }
    };

    Object.prototype.moveTo = function(x, y) {
      var bound;
      bound = this.arena.getBound();
      if (x > bound['x1'] && x < bound['x2'] && y > bound['y1'] && y < bound['y2']) {
        this.get().x = x;
        return this.get().y = y;
      } else {
        return console.log('invalid coordinates: (' + x + ',' + y + ')');
      }
    };

    Object.prototype.getRect = function() {
      var x1, x2, y1, y2;
      x1 = this.get().getBounds().x + this.get().x;
      y1 = this.get().getBounds().y + this.get().y;
      x2 = this.get().getBounds().x + this.get().x + this.get().getBounds().width;
      y2 = this.get().getBounds().y + this.get().y + this.get().getBounds().height;
      return {
        "x1": x1,
        "x2": x2,
        "y1": y1,
        "y2": y2
      };
    };

    Object.prototype.detectCollision = function() {
      var object, otherObject, rect1, rect2, _i, _len, _ref, _results;
      object = this.get;
      if (object == null) {
        return;
      }
      rect1 = object.getRect();
      _ref = this.arena.getObjects();
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        otherObject = _ref[_i];
        rect2 = otherObject.getRect();
        if (!((rect2.x2 < rect1.x1) || (rect2.x1 > rect1.x2) || (rect2.y1 > rect1.y2) || (rect2.y2 < rect1.y1))) {
          _results.push(this.collisionHandler(object, otherObject));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    Object.prototype.updateSpeed = function(a, b) {
      var v1, v2;
      v1 = a.speed;
      return v2 = b.speed;
    };

    a.reverseDirection();

    a.speed = Math.abs(a.mass - b.mass) / (a.mass + b.mass) * v1;

    a.speed += (2 * b.mass) / (a.mass + b.mass) * v2;

    b.reverseDirection();

    b.speed = (2 * b.mass) / (a.mass + b.mass) * v1;

    b.speed += Math.abs(a.mass - b.mass) / (a.mass + b.mass) * v2({
      collisionHandler: function() {
        return this.updateSpeed();
      }
    });

    return Object;

  })();

}).call(this);
