// Generated by CoffeeScript 1.7.1
(function() {
  var Player, object, player_schema,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  object = require("./object.js");

  player_schema = require("./characters/firzen.js");

  Player = (function(_super) {
    __extends(Player, _super);

    function Player(id, name, type, x, y, bound) {
      this.id = id;
      this.name = name;
      this.type = type;
      this.x = x;
      this.y = y;
      this.bound = bound;
      Player.__super__.constructor.call(this, this.name, this.type, this.x, this.y, this.bound);
      this.setupInfo(player_schema.info);
      this.hp = this.maxhp;
      this.score = 0;
      this.number;
      this.faceDirection = "right";
    }

    Player.prototype.init = function() {
      Player.__super__.init.apply(this, arguments);
      return this.spriteSheetInfo = player_schema.spriteSheetInfo;
    };

    Player.prototype.move = function(direction) {
      if (this.checkState()) {
        this.setState("run");
        this.speed = this.originSpeed;
        this.direction = direction;
        this.faceDirection = direction === "left" || direction === "ul" || direction === 'dl' ? "left" : "right";
        this.moveStep();
        return true;
      }
      return false;
    };

    Player.prototype.attack = function() {
      if (this.checkState()) {
        if (this.state !== "attack") {
          this.setState("attack");
          return true;
        }
      }
      return false;
    };

    Player.prototype.cast = function() {
      if (this.checkState() && this.magicState === 'ready') {
        this.magicState = 'preparing';
        if (this.state !== "cast") {
          this.setState("cast");
        }
        setTimeout(((function(_this) {
          return function() {
            return _this.magicState = "ready";
          };
        })(this)), this.cd);
        return true;
      }
      return false;
    };

    Player.prototype.rebirth = function() {
      this.idle();
      this.x = this.bound.x1 + Math.floor(Math.random() * (this.bound.x2 - this.bound.x1 - this.width));
      this.y = this.bound.y1 + Math.floor(Math.random() * (this.bound.y2 - this.bound.y1 - this.height));
      return this.hp = this.maxhp;
    };

    Player.prototype.idle = function() {
      this.state = 'idle';
      this.speed = 0;
      return this.direction = "No";
    };

    Player.prototype.gotHit = function(damage, direction) {
      if (this.state === "die") {
        return;
      }
      this.hp -= damage;
      if (this.hp <= 0) {
        this.setState('die');
        return this.score -= 30;
      } else {
        this.setState('hurt');
        this.faceDirection = direction;
        return this.moveStep(this.counterDirection(direction));
      }
    };

    Player.prototype.setState = function(state, animation) {
      if (animation == null) {
        animation = null;
      }
      this.state = state;
      if (animation !== null) {
        this.animation = animation;
      } else {
        if (state !== "idle" && state !== "run") {
          this.animation = state;
        }
      }
      switch (state) {
        case "idle":
          return this.idle();
        case "die":
          return setTimeout(((function(_this) {
            return function() {
              return _this.rebirth();
            };
          })(this)), this.animationTime());
        case "collided":
          return setTimeout((function() {
            return this.idle();
          }).bind(this), this.animationTime());
      }
    };

    Player.prototype.animationTime = function(act) {
      if (act == null) {
        act = null;
      }
      if (act === null) {
        act = this.state;
      }
      switch (act) {
        case 'die':
          return 3000;
        case 'collided':
          return 100;
        case 'cast':
          return 600;
        default:
          return null;
      }
    };

    Player.prototype.checkState = function() {
      var _ref;
      if ((_ref = this.state) === "disabled" || _ref === "collided" || _ref === "die" || _ref === "hurt") {
        return false;
      } else {
        return true;
      }
    };

    Player.prototype.collisionHandler = function(object, direction) {
      if (object.name !== "coin") {
        this.collide(direction);
      }
      if (object.state !== "collided") {
        return object.collisionHandler(this, this.counterDirection(direction));
      }
    };

    Player.prototype.getStatus = function() {
      this.info.x = this.x;
      this.info.y = this.y;
      this.info.state = this.state;
      this.info.animation = this.animation;
      this.info.direction = this.direction;
      this.info.faceDirection = this.faceDirection;
      this.info.hp = this.hp;
      this.info.cd = this.cd;
      this.info.score = this.score;
      return this.info;
    };

    return Player;

  })(object);

  module.exports = Player;

}).call(this);
