// Generated by CoffeeScript 1.7.1
(function() {
  var Magic, object, player_schema,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  object = require("./object.js");

  player_schema = require("./player_schema.js");

  Magic = (function(_super) {
    __extends(Magic, _super);

    function Magic(id, name, x, y, world, characterID, direction) {
      this.id = id;
      this.name = name;
      this.x = x;
      this.y = y;
      this.world = world;
      this.characterID = characterID;
      this.direction = direction;
      this.moveStep = __bind(this.moveStep, this);
      Magic.__super__.constructor.call(this, this.name, 'magic', this.x, this.y, this.world);
    }

    Magic.prototype.init = function() {
      this.originSpeed = 5;
      this.speed = this.originSpeed;
      this.damage = 10;
      this.collisionHeight = 0;
      this.collisionWidth = 0;
      this.width = 40;
      this.height = 40;
      this.state = "run";
      return this.magicSheetInfo = player_schema.magicSheetInfo;
    };

    Magic.prototype.collisionHandler = function(o) {
      if (o.id !== this.characterID) {
        o.gotHit(this.direction);
        console.log('hit player' + o.id);
        return this.state = "removed";
      }
    };

    Magic.prototype.moveStep = function(direction, speed) {
      if (direction == null) {
        direction = null;
      }
      if (speed == null) {
        speed = null;
      }
      if (direction === null) {
        direction = this.direction;
      }
      if (speed === null) {
        speed = this.speed;
      }
      switch (direction) {
        case "left":
          return this.x -= speed;
        case "right":
          return this.x += speed;
        case "down":
          return this.y += speed;
        case "up":
          return this.y -= speed;
      }
    };

    return Magic;

  })(object);

  module.exports = Magic;

}).call(this);
