// Generated by CoffeeScript 1.7.1
(function() {
  var object,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  object = (function() {
    function object(name, type, x, y, world) {
      this.name = name;
      this.type = type;
      this.x = x;
      this.y = y;
      this.world = world;
      this.moveStep = __bind(this.moveStep, this);
      this.id;
      this.type;
      this.hp;
      this.state = "idle";
      this.mass = 1;
      this.speed = 0;
      this.originSpeed = 2;
      this.collisionHeight = 20;
      this.collisionWidth = 30;
      this.spriteSheetInfo;
      this.direction;
      this.magicState = "ready";
      this.init();
    }

    object.prototype.init = function() {
      this.width;
      return this.height;
    };

    object.prototype.counterDirection = function(direction) {
      switch (direction) {
        case "right":
          return "left";
          break;
        case "left":
          return "right";
          break;
        case "up":
          return "down";
          break;
        case "down":
          return "up";
          break;
        case "No":
          return "No";
      }
    };

    object.prototype.reverseDirection = function() {
      return this.direction = this.counterDirection(this.direction);
    };

    object.prototype.moveStep = function(direction, speed) {
      var bound;
      if (direction == null) {
        direction = null;
      }
      if (speed == null) {
        speed = null;
      }
      bound = this.world.getBound();
      if (direction === null) {
        direction = this.direction;
      }
      if (speed === null) {
        speed = this.speed;
      }
      switch (direction) {
        case "left":
          if (this.direction !== "left") {
            this.direction = "left";
          }
          if (this.x - speed > bound['x1']) {
            return this.x -= speed;
          } else {
            return this.x += speed;
          }
          break;
        case "right":
          if (this.direction !== "right") {
            this.direction = "right";
          }
          if (this.x + speed < bound['x2']) {
            return this.x += speed;
          } else {
            return this.x -= speed;
          }
          break;
        case "down":
          this.direction = "down";
          if (this.y + speed < bound['y2']) {
            return this.y += speed;
          } else {
            return this.y -= speed;
          }
          break;
        case "up":
          this.direction = "up";
          if (this.y - speed > bound['y1']) {
            return this.y -= speed;
          } else {
            return this.y += speed;
          }
      }
    };

    object.prototype.moveTo = function(x, y) {
      var bound;
      bound = this.world.getBound();
      if (x > bound['x1'] && x < bound['x2'] && y > bound['y1'] && y < bound['y2']) {
        this.x = x;
        return this.y = y;
      } else {
        return console.log('invalid coordinates: (' + x + ',' + y + ')');
      }
    };

    object.prototype.getRect = function() {
      var x1, x2, y1, y2;
      x1 = this.x - this.width / 2;
      y1 = this.y - this.height / 2;
      x2 = this.x + this.width / 2;
      y2 = this.y + this.height / 2;
      return {
        "x1": x1,
        "x2": x2,
        "y1": y1,
        "y2": y2
      };
    };

    object.prototype.getCollisionRect = function() {
      var x1, x2, y1, y2;
      x1 = this.x - this.width / 2 + this.collisionWidth;
      y1 = this.y - this.height / 2 + this.collisionHeight;
      x2 = this.x + this.width / 2 - this.collisionWidth;
      y2 = this.y + this.height / 2 - this.collisionHeight;
      return {
        "x1": x1,
        "x2": x2,
        "y1": y1,
        "y2": y2
      };
    };

    object.prototype.gotHit = function(direction) {
      return console.log("got hit");
    };

    object.prototype.realtiveDirection = function(object) {
      if (object.x < this.get().x) {
        return "left";
      }
      if (object.x >= this.get().x) {
        return "right";
      }
    };

    object.prototype.collide = function(o) {
      var v1, v2;
      console.log(this.name + ' collide with ' + o.name);
      v1 = this.speed;
      v2 = o.speed;
      if (o.direction === "No") {
        o.direction = this.direction;
        o.moveStep(direction);
      } else {
        o.reverseDirection();
        o.moveStep();
      }
      o.speed = Math.abs(o.mass - this.mass) / (this.mass + o.mass) * v1;
      o.speed += (2 * this.mass) / (this.mass + o.mass) * v2;
      o.state = 'collided';
      return this.state = 'collided';
    };

    object.prototype.collisionHandler = function(object) {
      this.collide(object);
      return setTimeout(((function(_this) {
        return function() {
          if (_this.state === "collided") {
            _this.state = "idle";
          }
          if (object.state === "collided") {
            return object.state = "idle";
          }
        };
      })(this)).bind(this), 100);
    };

    return object;

  })();

  module.exports = object;

}).call(this);
