// Generated by CoffeeScript 1.7.1
(function() {
  var Robot, object, robot_schema,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  object = require("./object.js");

  robot_schema = require("./robot_schema.js");

  Robot = (function(_super) {
    __extends(Robot, _super);

    function Robot(id, name, type, x, y, world) {
      this.id = id;
      this.name = name;
      this.type = type;
      this.x = x;
      this.y = y;
      this.world = world;
      Robot.__super__.constructor.call(this, this.name, this.type, this.x, this.y, this.world);
      this.hp = 100;
      this.cd = 300;
      this.damage = 15;
      this.attackRange = 50;
      this.number;
      this.faceDirection = "right";
    }

    Robot.prototype.init = function() {
      Robot.__super__.init.apply(this, arguments);
      this.state = "idle";
      this.direction = "No";
      this.width = 80;
      this.height = 80;
      this.spriteSheetInfo = robot_schema.spriteSheetInfo;
      return this.magicSheetInfo = robot_schema.magicSheetInfo;
    };

    Robot.prototype.move = function(direction) {
      if (this.checkState()) {
        this.setState("run");
        this.speed = this.originSpeed;
        this.direction = direction;
        this.faceDirection = direction === "left" || direction === "ul" || direction === 'dl' ? "left" : "right";
        this.moveStep();
        return true;
      }
      return false;
    };

    Robot.prototype.attack = function() {
      if (this.checkState()) {
        if (this.state !== "attack") {
          this.state = "attack";
          return true;
        }
      }
      return false;
    };

    Robot.prototype.cast = function() {
      if (this.checkState() && this.magicState === 'ready') {
        this.magicState = 'preparing';
        if (this.state !== "cast") {
          this.state = "cast";
        }
        setTimeout(((function(_this) {
          return function() {
            return _this.magicState = "ready";
          };
        })(this)), this.cd);
        return true;
      }
      return false;
    };

    Robot.prototype.rebirth = function() {
      var bound;
      this.setState("idle");
      bound = this.world.getBound();
      this.x = Math.floor(Math.random() * bound.x2);
      this.y = Math.floor(Math.random() * bound.y2);
      return this.hp = 100;
    };

    Robot.prototype.idle = function() {
      this.setState('idle');
      this.speed = 0;
      return this.direction = "No";
    };

    Robot.prototype.gotHit = function(damage, direction) {
      console.log('current hp: ' + this.hp);
      this.hp -= damage;
      if (this.hp <= 0) {
        this.setState('die');
        return setTimeout(((function(_this) {
          return function() {
            return _this.rebirth();
          };
        })(this)), 3000);
      } else {
        this.setState('hurt');
        this.faceDirection = direction;
        return this.moveStep(this.counterDirection(direction));
      }
    };

    Robot.prototype.setState = function(state) {
      return this.state = state;
    };

    Robot.prototype.checkState = function() {
      var _ref;
      if ((_ref = this.state) === "disabled" || _ref === "collided") {
        return false;
      } else {
        return true;
      }
    };

    Robot.prototype.animationTime = function(act) {
      if (act == null) {
        act = null;
      }
      if (act === null) {
        act = this.state;
      }
      switch (act) {
        case 'hurt':
          return 200;
        case 'attack':
          return 500;
        case 'cast':
          return 500;
        default:
          return null;
      }
    };

    return Robot;

  })(object);

  module.exports = Robot;

}).call(this);
