// Generated by CoffeeScript 1.7.1
(function() {
  var World;

  World = (function() {
    function World(name) {
      this.name = name;
      this.objects = [];
      this.init();
    }

    World.prototype.init = function() {
      this.width = 800;
      this.height = 400;
      return this.backgroundURL = "/assets/background/1.png";
    };

    World.prototype.getBound = function() {
      return {
        "x1": 0,
        "x2": this.width,
        "y1": 0,
        "y2": this.height
      };
    };

    return World;

  })();

  module.exports = World;

}).call(this);
