// Generated by CoffeeScript 1.7.1
(function() {
  var Item, UUID, World;

  Item = require("./item.js");

  UUID = require('node-uuid');

  World = (function() {
    function World(name) {
      this.name = name;
      this.objects = [];
      this.init();
    }

    World.prototype.init = function() {
      var bound, item_id, rock;
      this.width = 800;
      this.height = 400;
      this.backgroundURL = "/assets/background/1.png";
      item_id = UUID();
      bound = this.getBound();
      rock = new Item(item_id, "rock", 300, 300, bound);
      return this.objects.push(rock);
    };

    World.prototype.getBound = function() {
      return {
        "x1": 0,
        "x2": this.width,
        "y1": 150,
        "y2": this.height
      };
    };

    return World;

  })();

  module.exports = World;

}).call(this);
